ghost:
  image: ghost:5.80.0
  url: https://blog.cloudmasa.com
  mysqlUser: ghost
  mysqlPassword: ghostpass
  mysqlDatabase: ghostdb
  mysqlHost: ghost-mysql

  persistence:
    enabled: true
    size: 5Gi
    storageClass: ebs-gp3-csi

mysql:
  image: mysql:8.0
  rootPassword: rootpass
  user: ghost
  password: ghostpass
  database: ghostdb

  persistence:
    enabled: true
    size: 5Gi
    storageClass: ebs-gp3-csi

ingress:
  enabled: true
  host: blog.cloudmasa.com
  acmArn: arn:aws:acm:us-east-1:YOUR_AWS_ACCOUNT_ID:certificate/YOUR_CERTIFICATE_ID
