apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghost
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ghost
  template:
    metadata:
      labels:
        app: ghost
    spec:
      containers:
        - name: ghost
          image: {{ .Values.ghost.image }}
          ports:
            - containerPort: 2368
          env:
            - name: url
              value: {{ .Values.ghost.url }}
            - name: database__client
              value: "mysql"
            - name: database__connection__host
              value: {{ .Values.ghost.mysql.host }}
            - name: database__connection__user
              value: {{ .Values.ghost.mysql.user }}
            - name: database__connection__password
              valueFrom:
                secretKeyRef:
                  name: ghost-secret
                  key: mysql-password
            - name: database__connection__database
              value: {{ .Values.ghost.mysql.database }}
          volumeMounts:
            - name: ghost-content
              mountPath: /var/lib/ghost/content
      volumes:
        - name: ghost-content
          persistentVolumeClaim:
            claimName: ghost-pvc
