apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghost
spec:
  replicas: {{ .Values.ghost.replicaCount }}
  selector:
    matchLabels:
      app: ghost
  template:
    metadata:
      labels:
        app: ghost
    spec:
      containers:
      - name: ghost
        image: {{ .Values.ghost.image }}
        env:
        - name: url
          value: {{ .Values.ghost.url }}
        - name: database__client
          value: mysql
        - name: database__connection__host
          value: {{ .Values.ghost.database.host }}
        - name: database__connection__user
          value: {{ .Values.ghost.database.user }}
        - name: database__connection__password
          value: {{ .Values.ghost.database.password }}
        - name: database__connection__database
          value: {{ .Values.ghost.database.name }}
        ports:
        - containerPort: 2368
        volumeMounts:
        - name: ghost-pvc
          mountPath: /var/lib/ghost/content
      volumes:
        - name: ghost-pvc
          persistentVolumeClaim:
            claimName: ghost-pvc
