apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghost
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ghost
  template:
    metadata:
      labels:
        app: ghost
    spec:
      containers:
        - name: ghost
          image: {{ .Values.ghost.image }}
          env:
            - name: url
              value: {{ .Values.ghost.url }}
            - name: database__client
              value: mysql
            - name: database__connection__host
              value: {{ .Values.ghost.mysqlHost }}
            - name: database__connection__user
              value: {{ .Values.ghost.mysqlUser }}
            - name: database__connection__password
              value: {{ .Values.ghost.mysqlPassword }}
            - name: database__connection__database
              value: {{ .Values.ghost.mysqlDatabase }}
          ports:
            - containerPort: 2368
          volumeMounts:
            - name: ghost-content
              mountPath: /var/lib/ghost/content
      volumes:
        - name: ghost-content
          persistentVolumeClaim:
            claimName: ghost-pvc
