apiVersion: v1
kind: PersistentVolume
metadata:
  name: ghost-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ebs-gp3-csi
  csi:
    driver: ebs.csi.aws.com
    volumeHandle: vol-04da706eb4d43c083  # <-- Replace with actual EBS volume ID
---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ebs-gp3-csi
  csi:
    driver: ebs.csi.aws.com
    volumeHandle: vol-04da706eb4d43c083  # <-- Replace with actual EBS volume ID
