{{- if and (.Values.ghost) (hasKey .Values.ghost "persistence") (hasKey .Values.ghost.persistence "enabled") (eq .Values.ghost.persistence.enabled true) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ghost-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.ghost.persistence.size | default "5Gi" }}
  storageClassName: {{ .Values.ghost.persistence.storageClass | default "ebs-gp3-csi" }}
{{- end }}

---

{{- if and (.Values.mysql) (hasKey .Values.mysql "persistence") (hasKey .Values.mysql.persistence "enabled") (eq .Values.mysql.persistence.enabled true) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.mysql.persistence.size | default "5Gi" }}
  storageClassName: {{ .Values.mysql.persistence.storageClass | default "ebs-gp3-csi" }}
{{- end }}
