{{- if .Values.ghost.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ghost-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.ghost.persistence.size | default "5Gi" }}
  storageClassName: {{ .Values.ghost.persistence.storageClass | default "gp2" }}
{{- end }}

---

{{- if .Values.mysql.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.mysql.persistence.size | default "5Gi" }}
  storageClassName: {{ .Values.mysql.persistence.storageClass | default "gp2" }}
{{- end }}
